<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\" />
    <Folder Include="UseCases\Reports\Commands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InclusiON.DTOs\InclusiON.DTOs.csproj" />
    <ProjectReference Include="..\InclusiON.Domain\InclusiON.Domain.csproj" />
    <ProjectReference Include="..\InclusiON.Shared\InclusiON.Shared.csproj" />
    <ProjectReference Include="..\InclusiON.SemanticSearch\InclusiON.SemanticSearch.csproj" />
  </ItemGroup>

</Project>
