<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.9.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />

		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />

		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />

		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InclusiON.Application\InclusiON.Application.csproj" />
    <ProjectReference Include="..\InclusiON.Data\InclusiON.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\Emails\**\*.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
