-- ============================================================================
-- Migración y Catálogo Oficial: InstitutionalRoles (Cargos Directivos Escolares)
-- InclusiON - Sprint de Configuración Institucional
-- ============================================================================

CREATE TABLE IF NOT EXISTS "InstitutionalRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(255) NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_InstitutionalRoles_Name" ON "InstitutionalRoles" ("Name");

-- Carga de los 4 cargos escolares oficiales
INSERT INTO "InstitutionalRoles" ("Id", "Name", "Description", "IsActive", "CreatedAt")
OVERRIDING SYSTEM VALUE
VALUES
    (1, 'Director / Directora', 'Máxima autoridad de la institución escolar o centro', TRUE, NOW()),
    (2, 'Vicedirector / Vicedirectora', 'Vicedirección y gestión académica/institucional', TRUE, NOW()),
    (3, 'Secretario / Secretaria', 'Administración de legajos, expedientes y documentación escolar', TRUE, NOW()),
    (4, 'Preceptor / Preceptora', 'Acompañamiento, asistencia y organización de la dinámica escolar', TRUE, NOW())
ON CONFLICT ("Name") DO NOTHING;

-- Limpieza preventiva en caso de que existieran roles desestimados
DELETE FROM "InstitutionalRoles" WHERE "Id" > 4 OR "Name" ILIKE '%coordinador%' OR "Name" ILIKE '%orientaci%';

-- Agregar columna InstitutionalRoleId a AdminInstitutions si no existe
ALTER TABLE "AdminInstitutions" ADD COLUMN IF NOT EXISTS "InstitutionalRoleId" integer NULL;

-- Clave foránea
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_AdminInstitutions_InstitutionalRoles_InstitutionalRoleId'
    ) THEN
        ALTER TABLE "AdminInstitutions"
        ADD CONSTRAINT "FK_AdminInstitutions_InstitutionalRoles_InstitutionalRoleId"
        FOREIGN KEY ("InstitutionalRoleId") REFERENCES "InstitutionalRoles" ("Id")
        ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_AdminInstitutions_InstitutionalRoleId" ON "AdminInstitutions" ("InstitutionalRoleId");

-- Registrar en historial de migraciones de EF Core
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261004000000_AddInstitutionalRolesCatalog', '10.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;
