//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InclusiON.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InclusiON.Shared.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }

        public static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }

        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }

        public static string AccountLockedMinutes {
            get {
                return ResourceManager.GetString("AccountLockedMinutes", resourceCulture);
            }
        }

        public static string TwoFactorRequired {
            get {
                return ResourceManager.GetString("TwoFactorRequired", resourceCulture);
            }
        }

        public static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }

        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }

        public static string TokenRevoked {
            get {
                return ResourceManager.GetString("TokenRevoked", resourceCulture);
            }
        }

        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }

        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }

        public static string AccountDeactivated {
            get {
                return ResourceManager.GetString("AccountDeactivated", resourceCulture);
            }
        }

        public static string PasswordsMismatch {
            get {
                return ResourceManager.GetString("PasswordsMismatch", resourceCulture);
            }
        }

        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }

        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }

        public static string DocumentAlreadyExists {
            get {
                return ResourceManager.GetString("DocumentAlreadyExists", resourceCulture);
            }
        }

        public static string PinNotConfigured {
            get {
                return ResourceManager.GetString("PinNotConfigured", resourceCulture);
            }
        }

        public static string PinIncorrect {
            get {
                return ResourceManager.GetString("PinIncorrect", resourceCulture);
            }
        }

        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }

        public static string SupervisorInvalidCredentials {
            get {
                return ResourceManager.GetString("SupervisorInvalidCredentials", resourceCulture);
            }
        }

        public static string SupervisorNotAuthorized {
            get {
                return ResourceManager.GetString("SupervisorNotAuthorized", resourceCulture);
            }
        }

        public static string SupervisorAccountLocked {
            get {
                return ResourceManager.GetString("SupervisorAccountLocked", resourceCulture);
            }
        }

        public static string SupervisorMustBeProfessionalOrFamily {
            get {
                return ResourceManager.GetString("SupervisorMustBeProfessionalOrFamily", resourceCulture);
            }
        }

        public static string LoginMethodNotFound {
            get {
                return ResourceManager.GetString("LoginMethodNotFound", resourceCulture);
            }
        }

        public static string LoginMethodNotAvailable {
            get {
                return ResourceManager.GetString("LoginMethodNotAvailable", resourceCulture);
            }
        }

        public static string LoginMethodNotSupported {
            get {
                return ResourceManager.GetString("LoginMethodNotSupported", resourceCulture);
            }
        }

        public static string PinRequiredForMethod {
            get {
                return ResourceManager.GetString("PinRequiredForMethod", resourceCulture);
            }
        }

        public static string PinInvalidFormat {
            get {
                return ResourceManager.GetString("PinInvalidFormat", resourceCulture);
            }
        }

        public static string SupervisorRequiredForAssisted {
            get {
                return ResourceManager.GetString("SupervisorRequiredForAssisted", resourceCulture);
            }
        }

        public static string LoginMethodDeprecated {
            get {
                return ResourceManager.GetString("LoginMethodDeprecated", resourceCulture);
            }
        }

        public static string MethodNotAvailable {
            get {
                return ResourceManager.GetString("MethodNotAvailable", resourceCulture);
            }
        }

        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }

        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }

        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }

        public static string InternalErrorLogin {
            get {
                return ResourceManager.GetString("InternalErrorLogin", resourceCulture);
            }
        }

        public static string InternalErrorRegister {
            get {
                return ResourceManager.GetString("InternalErrorRegister", resourceCulture);
            }
        }

        public static string InternalErrorRefreshToken {
            get {
                return ResourceManager.GetString("InternalErrorRefreshToken", resourceCulture);
            }
        }

        public static string InternalErrorCreatePerson {
            get {
                return ResourceManager.GetString("InternalErrorCreatePerson", resourceCulture);
            }
        }

        public static string InternalErrorUpdatePerson {
            get {
                return ResourceManager.GetString("InternalErrorUpdatePerson", resourceCulture);
            }
        }

        public static string InternalErrorGetPerson {
            get {
                return ResourceManager.GetString("InternalErrorGetPerson", resourceCulture);
            }
        }

        public static string InternalErrorListPersons {
            get {
                return ResourceManager.GetString("InternalErrorListPersons", resourceCulture);
            }
        }

        public static string InternalErrorGetProfile {
            get {
                return ResourceManager.GetString("InternalErrorGetProfile", resourceCulture);
            }
        }

        public static string InternalErrorIdentifyUser {
            get {
                return ResourceManager.GetString("InternalErrorIdentifyUser", resourceCulture);
            }
        }

        public static string InternalErrorGetLoginMethods {
            get {
                return ResourceManager.GetString("InternalErrorGetLoginMethods", resourceCulture);
            }
        }

        public static string InternalErrorUpdateLoginMethod {
            get {
                return ResourceManager.GetString("InternalErrorUpdateLoginMethod", resourceCulture);
            }
        }

        public static string UserCreationError {
            get {
                return ResourceManager.GetString("UserCreationError", resourceCulture);
            }
        }
    }
}
