//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InclusiON.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InclusiON.Shared.Resources.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login asistido exitoso.
        /// </summary>
        public static string AssistedLoginSuccessful {
            get {
                return ResourceManager.GetString("AssistedLoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodos de login obtenidos correctamente.
        /// </summary>
        public static string LoginMethodsRetrieved {
            get {
                return ResourceManager.GetString("LoginMethodsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo de login actualizado correctamente.
        /// </summary>
        public static string LoginMethodUpdated {
            get {
                return ResourceManager.GetString("LoginMethodUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login succesfull.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona creada exitosamente.
        /// </summary>
        public static string PersonCreated {
            get {
                return ResourceManager.GetString("PersonCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona actualizada exitosamente.
        /// </summary>
        public static string PersonUpdated {
            get {
                return ResourceManager.GetString("PersonUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed successfully.
        /// </summary>
        public static string TokenRefreshed {
            get {
                return ResourceManager.GetString("TokenRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario identificado correctamente.
        /// </summary>
        public static string UserIdentified {
            get {
                return ResourceManager.GetString("UserIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login exitoso.
        /// </summary>
        public static string VisualLoginSuccessful {
            get {
                return ResourceManager.GetString("VisualLoginSuccessful", resourceCulture);
            }
        }
    }
}
