// <auto-generated />
using System;
using InclusiON.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InclusiON.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105000227_AddAuthenticationSystem")]
    partial class AddAuthenticationSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InclusiON.Entities.Models.AccessAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AccessedPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AffectedRecordId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AffectedTable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessedPersonId");

                    b.HasIndex("ActionType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AccessAudits", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplexityLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("HasAudioSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasVisualSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Instructions")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStandardActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresSupervision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ResourcesUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UsesEasyReading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("UsesPictograms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedByProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEvaluationActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AssignedByProfessionalId");

                    b.HasIndex("PersonId");

                    b.HasIndex("Status");

                    b.ToTable("ActivityAssignments", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActivityCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Actividades de lectura, escritura, conciencia fonológica y comprensión lectora",
                            IsActive = true,
                            Name = "Lectoescritura"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Actividades prenuméricas, numeración, secuencias y operaciones básicas",
                            IsActive = true,
                            Name = "Numeración y Matemática"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modificación de conducta, hábitos, rutinas, normas de convivencia e historias sociales",
                            IsActive = true,
                            Name = "Habilidades Socioemocionales"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lengua de señas, sistemas aumentativos y alternativos de comunicación (SAAC)",
                            IsActive = true,
                            Name = "Comunicación y Lenguaje"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Motricidad fina, motricidad gruesa, coordinación óculo-manual y orientación espacial",
                            IsActive = true,
                            Name = "Motricidad y Coordinación"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Música, plástica y dramatización",
                            IsActive = true,
                            Name = "Creatividad y Expresión Artística"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vestimenta, higiene, manejo del dinero, noción del tiempo y situaciones cotidianas",
                            IsActive = true,
                            Name = "Autonomía y Vida Diaria"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Memoria, atención, percepción y resolución de problemas",
                            IsActive = true,
                            Name = "Estimulación Cognitiva"
                        });
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrustrationLevel")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("RequiredSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ResponsePattern")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SuccessPercentage")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("ActivityResponses", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.AutonomyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresSupervision")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AutonomyLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Puede usar la aplicacion de forma independiente con login estandar",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Alta",
                            RequiresSupervision = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "Requiere login simplificado (PIN o pictogramas) pero puede usar la app solo",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Media",
                            RequiresSupervision = false
                        },
                        new
                        {
                            Id = 3,
                            Description = "Requiere supervision y login asistido por familiar o profesional",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Baja",
                            RequiresSupervision = true
                        });
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentifiedCapabilities")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("IdentifiedChallenges")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("InitialObservations")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PedagogicalObjectives")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryDiagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecommendedStrategies")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("RequiredSupports")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Diagnoses", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.DisabilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DisabilityTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Incluye discapacidad auditiva y visual (sordera, ceguera)",
                            IsActive = true,
                            Name = "Sensorial"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Relacionada con el aprendizaje y habilidades adaptativas de la vida diaria",
                            IsActive = true,
                            Name = "Cognitiva/Intelectual"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Alteraciones en el funcionamiento motor",
                            IsActive = true,
                            Name = "Motriz"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Derivada de diagnósticos vinculados a la salud mental",
                            IsActive = true,
                            Name = "Mental/Psicosocial"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Combinación de dos o más tipos de discapacidad",
                            IsActive = true,
                            Name = "Múltiple"
                        });
                });

            modelBuilder.Entity("InclusiON.Entities.Models.EducationalInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EducationalInstitutions", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.FamilyRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasFilter("[DocumentNumber] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FamilyRepresentatives", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ForPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByProfessionalId");

                    b.HasIndex("Email");

                    b.HasIndex("ForPersonId");

                    b.HasIndex("UsedByUserId");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.LoginMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MinAutonomyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPictogram")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPin")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSupervisor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LoginMethods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "STANDARD",
                            Description = "Login tradicional con email y contrasena",
                            DisplayOrder = 1,
                            IsActive = true,
                            MinAutonomyLevel = 1,
                            Name = "Email y Contrasena",
                            RequiresEmail = true,
                            RequiresPassword = true,
                            RequiresPictogram = false,
                            RequiresPin = false,
                            RequiresSupervisor = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "PIN",
                            Description = "Login con nombre de usuario y PIN de 4-6 digitos",
                            DisplayOrder = 2,
                            IsActive = true,
                            MinAutonomyLevel = 2,
                            Name = "PIN Numerico",
                            RequiresEmail = false,
                            RequiresPassword = false,
                            RequiresPictogram = false,
                            RequiresPin = true,
                            RequiresSupervisor = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "PICTOGRAM",
                            Description = "Login seleccionando una secuencia de imagenes",
                            DisplayOrder = 3,
                            IsActive = true,
                            MinAutonomyLevel = 2,
                            Name = "Secuencia de Pictogramas",
                            RequiresEmail = false,
                            RequiresPassword = false,
                            RequiresPictogram = true,
                            RequiresPin = false,
                            RequiresSupervisor = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "SUPERVISED",
                            Description = "Login requiere desbloqueo por familiar o profesional",
                            DisplayOrder = 4,
                            IsActive = true,
                            MinAutonomyLevel = 3,
                            Name = "Supervisado",
                            RequiresEmail = false,
                            RequiresPassword = false,
                            RequiresPictogram = false,
                            RequiresPin = false,
                            RequiresSupervisor = true
                        },
                        new
                        {
                            Id = 5,
                            Code = "TRUSTED_DEVICE",
                            Description = "Login automatico en dispositivos previamente autorizados",
                            DisplayOrder = 5,
                            IsActive = true,
                            MinAutonomyLevel = 3,
                            Name = "Dispositivo Confiable",
                            RequiresEmail = false,
                            RequiresPassword = false,
                            RequiresPictogram = false,
                            RequiresPin = false,
                            RequiresSupervisor = false
                        });
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("RelatedPersonId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.PersonRepresentative", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanSuperviseLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ConsentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasInformedConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("PersonId", "RepresentativeId");

                    b.HasIndex("RepresentativeId");

                    b.ToTable("PersonRepresentatives", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.PersonWithDisability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalTherapies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("AttentionLevel")
                        .HasColumnType("int");

                    b.Property<int?>("AutonomyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("AvailableResources")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CommunicationLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DisabilityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InterestsAndMotivators")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LearningStyle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LoginMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("MotorSkillLevel")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PictogramSequence")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PinCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("RequiresHighContrast")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresLargeFont")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("SoundSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("SupervisorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UsesAAC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("UsesSignLanguage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("VisualNoiseSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AutonomyLevelId");

                    b.HasIndex("DisabilityTypeId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasFilter("[DocumentNumber] IS NOT NULL");

                    b.HasIndex("LoginMethodId");

                    b.HasIndex("SupervisorUserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonsWithDisability", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasFilter("[DocumentNumber] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Professionals", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ProfessionalInstitution", b =>
                {
                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ProfessionalId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("ProfessionalInstitutions", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ProfessionalPerson", b =>
                {
                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CanSuperviseLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimaryProfessional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ProfessionalId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ProfessionalPersons", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievedGoals")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("AreasToReinforce")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FutureRecommendations")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NextObjectives")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("PeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReportTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Informe de estandarización y diagnóstico inicial del estudiante",
                            IsActive = true,
                            Name = "Evaluación Inicial"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Informe de progreso mensual",
                            IsActive = true,
                            Name = "Seguimiento Mensual"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Evaluación de progreso trimestral",
                            IsActive = true,
                            Name = "Informe Trimestral"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Proyecto Pedagógico Individual para la inclusión",
                            IsActive = true,
                            Name = "PPI"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Resumen anual de logros alcanzados y áreas a reforzar",
                            IsActive = true,
                            Name = "Informe Anual"
                        });
                });

            modelBuilder.Entity("InclusiON.Entities.Models.TrustedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AuthorizedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizedByUserId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("TrustedDevices", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoginIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LastLoginUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Professional",
                            NormalizedName = "PROFESSIONAL"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "FamilyRepresentative",
                            NormalizedName = "FAMILYREPRESENTATIVE"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "PersonWithDisability",
                            NormalizedName = "PERSONWITHDISABILITY"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InclusiON.Entities.Models.AccessAudit", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "AccessedPerson")
                        .WithMany("AccessAudits")
                        .HasForeignKey("AccessedPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "User")
                        .WithMany("AccessAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessedPerson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Activity", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.ActivityCategory", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.Professional", "Professional")
                        .WithMany("Activities")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityAssignment", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.Activity", "Activity")
                        .WithMany("ActivityAssignments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.Professional", "AssignedByProfessional")
                        .WithMany("ActivityAssignments")
                        .HasForeignKey("AssignedByProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "Person")
                        .WithMany("ActivityAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("AssignedByProfessional");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityResponse", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.ActivityAssignment", "Assignment")
                        .WithMany("Responses")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Diagnosis", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "Person")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.Professional", "Professional")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.FamilyRepresentative", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", "User")
                        .WithOne("FamilyRepresentative")
                        .HasForeignKey("InclusiON.Entities.Models.FamilyRepresentative", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Invitation", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.Professional", "CreatedByProfessional")
                        .WithMany("CreatedInvitations")
                        .HasForeignKey("CreatedByProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "ForPerson")
                        .WithMany()
                        .HasForeignKey("ForPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByProfessional");

                    b.Navigation("ForPerson");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Message", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.Message", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "RelatedPerson")
                        .WithMany("RelatedMessages")
                        .HasForeignKey("RelatedPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentMessage");

                    b.Navigation("Receiver");

                    b.Navigation("RelatedPerson");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.PersonRepresentative", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "Person")
                        .WithMany("PersonRepresentatives")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.FamilyRepresentative", "Representative")
                        .WithMany("PersonRepresentatives")
                        .HasForeignKey("RepresentativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.PersonWithDisability", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.AutonomyLevel", "AutonomyLevel")
                        .WithMany("PersonsWithDisability")
                        .HasForeignKey("AutonomyLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.DisabilityType", "DisabilityType")
                        .WithMany("PersonsWithDisability")
                        .HasForeignKey("DisabilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.LoginMethod", "LoginMethod")
                        .WithMany("PersonsWithDisability")
                        .HasForeignKey("LoginMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "SupervisorUser")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "User")
                        .WithOne("PersonWithDisability")
                        .HasForeignKey("InclusiON.Entities.Models.PersonWithDisability", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AutonomyLevel");

                    b.Navigation("DisabilityType");

                    b.Navigation("LoginMethod");

                    b.Navigation("SupervisorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Professional", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", "User")
                        .WithOne("Professional")
                        .HasForeignKey("InclusiON.Entities.Models.Professional", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ProfessionalInstitution", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.EducationalInstitution", "Institution")
                        .WithMany("ProfessionalInstitutions")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.Professional", "Professional")
                        .WithMany("ProfessionalInstitutions")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ProfessionalPerson", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "Person")
                        .WithMany("ProfessionalPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.Professional", "Professional")
                        .WithMany("ProfessionalPersons")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.RefreshToken", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Report", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.PersonWithDisability", "Person")
                        .WithMany("Reports")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.Professional", "Professional")
                        .WithMany("Reports")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Professional");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.TrustedDevice", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", "AuthorizedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InclusiON.Entities.Models.User", "User")
                        .WithMany("TrustedDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InclusiON.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("InclusiON.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Activity", b =>
                {
                    b.Navigation("ActivityAssignments");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityAssignment", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ActivityCategory", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.AutonomyLevel", b =>
                {
                    b.Navigation("PersonsWithDisability");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.DisabilityType", b =>
                {
                    b.Navigation("PersonsWithDisability");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.EducationalInstitution", b =>
                {
                    b.Navigation("ProfessionalInstitutions");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.FamilyRepresentative", b =>
                {
                    b.Navigation("PersonRepresentatives");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.LoginMethod", b =>
                {
                    b.Navigation("PersonsWithDisability");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Message", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.PersonWithDisability", b =>
                {
                    b.Navigation("AccessAudits");

                    b.Navigation("ActivityAssignments");

                    b.Navigation("Diagnoses");

                    b.Navigation("PersonRepresentatives");

                    b.Navigation("ProfessionalPersons");

                    b.Navigation("RelatedMessages");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.Professional", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivityAssignments");

                    b.Navigation("CreatedInvitations");

                    b.Navigation("Diagnoses");

                    b.Navigation("ProfessionalInstitutions");

                    b.Navigation("ProfessionalPersons");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("InclusiON.Entities.Models.User", b =>
                {
                    b.Navigation("AccessAudits");

                    b.Navigation("FamilyRepresentative");

                    b.Navigation("PersonWithDisability");

                    b.Navigation("Professional");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentMessages");

                    b.Navigation("TrustedDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
